In [6]:
import numpy as np

In [8]:
a = np.array([[
    [1,2,3],[12,34,34]
]])

b = np.array([[
    [12,32],
    [34,45]
]])

c = np.array ([
    [12,32],
    [12,23]
])

In [10]:
np.zeros((4, 2)) 

array([[0., 0.],
       [0., 0.]])

In [12]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [15]:
np.full((3,3),True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [20]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [21]:
np.arange(1,5)

array([1, 2, 3, 4])

In [22]:
np.arange(1,20,5)

array([ 1,  6, 11, 16])

In [26]:
np.linspace(1,20,9)

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

In [29]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [43]:
d = np.array([1,2,3,4,5,6,7])
np.reshape(d,(7,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [20]:
a = np.array([1,2,23,4,5,5,4,3,2,12,2,2])
np.reshape(a, (-1,4))

array([[ 1,  2, 23,  4],
       [ 5,  5,  4,  3],
       [ 2, 12,  2,  2]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [47]:
np.eye(3,4,k = 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
e = np.array([ 
    [12,34,12],[12,354,66],[12,44,21],[24,232,45]
])

In [4]:
np.ravel(e)

array([ 12,  34,  12,  12, 354,  66,  12,  44,  21,  24, 232,  45])

In [3]:
arr = np.array([[1, 2], [3, 4]])
flat = arr.flatten()

print("Original:", arr)
print("Flattened:", flat)

Original: [[1 2]
 [3 4]]
Flattened: [1 2 3 4]


In [21]:
a = [(1,2,3,5)]
np.resize(a,(2,3))

array([[1, 2, 3],
       [5, 1, 2]])

In [36]:
a = np.array([[1,2],[9,4]])
print("original:\n",a)
print("Transposition: \n",a.T)

original:
 [[1 2]
 [9 4]]
Transposition: 
 [[1 9]
 [2 4]]


In [7]:
emp_list = np.empty((4,6))
print(emp_list)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 7.56595733e-307
  1.89146896e-307 7.56571288e-307]
 [3.11525958e-307 1.24610723e-306 1.37962320e-306 1.29060871e-306
  2.22518251e-306 1.33511969e-306]
 [1.78022342e-306 1.05700345e-307 3.11525958e-307 1.69118108e-306
  8.06632139e-308 1.20160711e-306]
 [1.69119330e-306 1.29062229e-306 1.24610383e-306 1.33510679e-306
  1.37961709e-306 2.56765117e-312]]


In [12]:
emp_alike = np.empty_like(e)
print(emp_alike)

[[      1949551509576                  50                   0]
 [                  0                   0 7146768841584043371]
 [3270516248456554040 3978706164562159153 3471484086904827193]
 [3559595645083411250 8386112019185689144               29557]]


In [13]:
arr_shape = np.arange(95)

In [14]:
arr_shape

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94])

In [24]:
np.reshape(arr_shape,(-1,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94]])

In [12]:
m1 = np.array([[3,4]])
m2 = np.array([[6,4]])
m3 = np.array([[2,9]])

result = np.vstack((m1,m2,m3))
print(result)

[[3 4]
 [6 4]
 [2 9]]


In [13]:
np.hstack((m1,m2,m3))

array([[3, 4, 6, 4, 2, 9]])

In [14]:
col_1 = np.array([1,2,3])
col_2 = np.array([4,5,6])

In [15]:
np.column_stack((col_1,col_2))

array([[1, 4],
       [2, 5],
       [3, 6]])