In [2]:
import numpy as np

In [20]:
ar1 = np.array([1,2,21,34])
ar2 = np.array([2,4,2,12])

                            # Athermatic operation

In [21]:
ar1 + ar2

array([ 3,  6, 23, 46])

In [22]:
ar1 ** ar2

array([                  1,                  16,                 441,
       2386420683693101056])

In [23]:
ar1 - ar2

array([-1, -2, 19, 22])

In [24]:
ar1 * ar2

array([  2,   8,  42, 408])

In [25]:
ar1 / ar2

array([ 0.5       ,  0.5       , 10.5       ,  2.83333333])

In [27]:
a = np.array([[1,2,3],
            [1,4,67],
            [32,1,23]])

In [28]:
np.sum(a)

np.int64(134)

In [29]:
np.max(a)

np.int64(67)

In [30]:
np.min(a)

np.int64(1)

In [31]:
np.mean(a)

np.float64(14.88888888888889)

In [32]:
np.std(a)

np.float64(21.288726512950696)

In [10]:
ar3 = np.array([[1,2],[3,5]])
ar4 = np.array([[2,5]])
ar5 = np.array([[3,7]])
arr_1 = np.vstack((ar3,ar4,ar5))

In [11]:
arr_1

array([[1, 2],
       [3, 5],
       [2, 5],
       [3, 7]])

In [13]:
st1 = np.array([[1,2],[4,5]])
st2 = np.array([[7,9],[6,4]])
arr_2 = np.hstack((st1,st2))

In [14]:
arr_2

array([[1, 2, 7, 9],
       [4, 5, 6, 4]])

In [17]:
li_1 = np.arange(9)
np.split(li_1,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [15]:
arr = np.array([[1,23,445],
                [33,17,5]])

In [16]:
np.var(arr)

np.float64(25699.22222222223)

In [14]:
np.percentile(arr,100)

np.float64(445.0)

In [17]:
np.sum(arr,axis = 0)

array([ 34,  40, 450])

In [18]:
np.sum(arr,axis = 1)

array([469,  55])

In [52]:
data = np.array([10,20,30,40,50])

In [53]:
value = data>25
print(value)
print(data[value])

[False False  True  True  True]
[30 40 50]


In [54]:
value1 = (data > 25) & (data < 40)

In [55]:
(data[value1])

array([30])

In [56]:
marks = np.array([87,44,32,69,65,32])

In [57]:
marks + 5

array([92, 49, 37, 74, 70, 37])

In [60]:
np.where(data>25, data + 5,data)

array([10, 20, 35, 45, 55])

In [3]:
a = np.array([[1,2],
             [2,4]])

b = np.array([[4,5],
              [3,2]])


In [4]:
np.dot(a,b)

array([[10,  9],
       [20, 18]])

                                 #Inverse matrix
                                 ##Formula 
                                 A^-1 = 1
                                       ____  =    [d -b]
                                       ad-bc      [-c a]  
    

In [13]:
inv_det = ([[4,1],
           [4,2]])


In [11]:
np.linalg.inv(inv_det)


array([[ 0.5 , -0.25],
       [-1.  ,  1.  ]])

In [14]:
np.linalg.det(inv_det)

np.float64(4.0)

5x + 3y = 4
4x + 2y = 1
a = [5 3]
    [4,2]  
    
b = [4]
    [1]

x =  [x]
     [y]

In [17]:
x = np.array([[5,3],
             [4,2]])
y = np.array([4,1])
np.linalg.solve(x,y)

array([-2.5,  5.5])

In [18]:
np.load('data.npy')

array([10, 12, 15])