In [1]:
import numpy as np

In [4]:
a = np.array([10,12,15])
np.save('data.npy',a) # for single dataset 

In [5]:
np.load('data.npy') 

array([10, 12, 15])

In [9]:
b = np.array([[24,43,12], [32,45,19]])
np.savez('m_data.npz',x_data = b)

In [10]:
np.load('data.npy')
#np.load('m_data.npz')

array([10, 12, 15])

In [11]:
data = np.load('m_data.npz')
print(data['x_data'])

[[24 43 12]
 [32 45 19]]


In [9]:
c = np.array([[12,34,124],
             [76,32,198]])
np.savetxt('file.csv',c,delimiter = ',')

In [12]:
np.loadtxt('file.csv',delimiter = ',')

array([[ 12.,  34., 124.],
       [ 76.,  32., 198.]])

In [25]:
with_space = ([[12,34,56,43],
              [85,21,243,434]])
np.savetxt('with_space.txt',with_space,delimiter = ' ')

s_data = np.loadtxt('with_space.txt',delimiter = ' ')
print(s_data)

[[ 12.  34.  56.  43.]
 [ 85.  21. 243. 434.]]


In [12]:
import numpy as np

p_data = np.array([[72,43,56,65],
                   [45,64,35,61]])

np.savetxt('with_header.txt', p_data, delimiter = ',',
           header='maths,english,chemistry,physic', fmt='%d')

# Skip the header row
d = np.loadtxt('with_header.txt', delimiter=',')
print(d)


[[72. 43. 56. 65.]
 [45. 64. 35. 61.]]
