In [2]:
import numpy as np

In [2]:
np.random.rand(5)

array([0.79601231, 0.82643078, 0.03902196, 0.20374081, 0.11756947])

In [28]:
np.random.rand(2,4)

array([[0.23625628, 0.30665067, 0.76036546, 0.54807881],
       [0.46810074, 0.87111748, 0.15556643, 0.33589453]])

In [29]:
np.random.randint(20,100,size = 10)

array([62, 64, 97, 91, 68, 22, 24, 38, 68, 71], dtype=int32)

In [9]:
np.random.randint(20,50, size = (3,3))

array([[25, 26, 31],
       [35, 41, 29],
       [20, 47, 22]], dtype=int32)

In [12]:
np.random.choice([1,2,3,4,5],size = 3,replace = False )

array([3, 4, 5])

In [2]:
colors = ['green', 'grey', 'orange']
probabilities = [0.1, 0.3, 0.6]  # green is most likely

picked = np.random.choice(colors, size=10, p=probabilities)
print(picked)

['grey' 'orange' 'orange' 'grey' 'grey' 'orange' 'orange' 'orange'
 'orange' 'grey']


In [21]:
a = np.array([12,34,22,123])
np.random.choice(a,size = 2,replace = False)

array([ 12, 123])

In [13]:
np.random.normal(0,5,size = 4)

array([ 2.60748735, -2.22925904,  9.71252712,  7.02962723])

In [14]:
ab = np.array([11,22,34,12,123,23])
np.random.shuffle(ab)
print(ab)

[ 34  12  23  11 123  22]


In [29]:
np.random.uniform(10, 20, size=5)

array([12.29577214, 15.34413909, 19.13962025, 14.57204808, 14.30698567])

In [30]:
np.random.uniform(-5, 5, size=(2, 3))

array([[ 4.39127789,  2.78389236,  2.15970516],
       [ 3.02757504, -4.07199191,  0.18152549]])

In [3]:
outcomes = ['HEADS','TRIALS']
PROBABILITIES = [0.5,0.5]
b = np.random.choice(outcomes,size = 10,p = PROBABILITIES)
print(b)

['HEADS' 'TRIALS' 'TRIALS' 'TRIALS' 'TRIALS' 'HEADS' 'HEADS' 'HEADS'
 'HEADS' 'TRIALS']


In [3]:
np.random.seed(21)
print(np.random.randint(1, 10, 3))


[9 5 1]
